#############################################################################
# Makefile for building: hw4.app/Contents/MacOS/hw4
# Generated by qmake (2.01a) (Qt 4.6.4) on: Sun Apr 22 17:27:27 2012
# Project:  hw4.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile hw4.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.6/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch i386
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = attacker.cpp \
		blocker.cpp \
		enemy.cpp \
		main.cpp \
		medpack.cpp \
		player.cpp \
		zombie.cpp \
		zombie_invasion.cpp \
		smartattacker.cpp moc_zombie_invasion.cpp
OBJECTS       = attacker.o \
		blocker.o \
		enemy.o \
		main.o \
		medpack.o \
		player.o \
		zombie.o \
		zombie_invasion.o \
		smartattacker.o \
		moc_zombie_invasion.o
DIST          = /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		hw4.pro
QMAKE_TARGET  = hw4
DESTDIR       = 
TARGET        = hw4.app/Contents/MacOS/hw4

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		i386 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile hw4.app/Contents/PkgInfo hw4.app/Contents/Resources/empty.lproj hw4.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) hw4.app/Contents/MacOS/ || $(MKDIR) hw4.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hw4.pro  /usr/local/Qt4.6/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile hw4.pro
/usr/local/Qt4.6/mkspecs/common/unix.conf:
/usr/local/Qt4.6/mkspecs/common/mac.conf:
/usr/local/Qt4.6/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.6/mkspecs/qconfig.pri:
/usr/local/Qt4.6/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.6/mkspecs/features/qt_config.prf:
/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.6/mkspecs/features/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.6/mkspecs/features/debug.prf:
/usr/local/Qt4.6/mkspecs/features/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/x86.prf:
/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.6/mkspecs/features/warn_on.prf:
/usr/local/Qt4.6/mkspecs/features/qt.prf:
/usr/local/Qt4.6/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.6/mkspecs/features/moc.prf:
/usr/local/Qt4.6/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.6/mkspecs/features/resources.prf:
/usr/local/Qt4.6/mkspecs/features/uic.prf:
/usr/local/Qt4.6/mkspecs/features/yacc.prf:
/usr/local/Qt4.6/mkspecs/features/lex.prf:
/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile hw4.pro

hw4.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) hw4.app/Contents || $(MKDIR) hw4.app/Contents 
	@$(DEL_FILE) hw4.app/Contents/PkgInfo
	@echo "APPL????" >hw4.app/Contents/PkgInfo
hw4.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) hw4.app/Contents/Resources || $(MKDIR) hw4.app/Contents/Resources 
	@touch hw4.app/Contents/Resources/empty.lproj
	
hw4.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) hw4.app/Contents || $(MKDIR) hw4.app/Contents 
	@$(DEL_FILE) hw4.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,hw4,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.6/mkspecs/macx-g++/Info.plist.app >hw4.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/hw41.0.0 || $(MKDIR) .tmp/hw41.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hw41.0.0/ && $(COPY_FILE) --parents attacker.h blocker.h enemy.h medpack.h player.h zombie.h zombie_invasion.h smartattacker.h .tmp/hw41.0.0/ && $(COPY_FILE) --parents attacker.cpp blocker.cpp enemy.cpp main.cpp medpack.cpp player.cpp zombie.cpp zombie_invasion.cpp smartattacker.cpp .tmp/hw41.0.0/ && (cd `dirname .tmp/hw41.0.0` && $(TAR) hw41.0.0.tar hw41.0.0 && $(COMPRESS) hw41.0.0.tar) && $(MOVE) `dirname .tmp/hw41.0.0`/hw41.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hw41.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r hw4.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_zombie_invasion.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_zombie_invasion.cpp
moc_zombie_invasion.cpp: enemy.h \
		player.h \
		zombie.h \
		blocker.h \
		medpack.h \
		attacker.h \
		smartattacker.h \
		zombie_invasion.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ zombie_invasion.h -o moc_zombie_invasion.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

attacker.o: attacker.cpp attacker.h \
		enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o attacker.o attacker.cpp

blocker.o: blocker.cpp blocker.h \
		enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blocker.o blocker.cpp

enemy.o: enemy.cpp enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enemy.o enemy.cpp

main.o: main.cpp zombie_invasion.h \
		enemy.h \
		player.h \
		zombie.h \
		blocker.h \
		medpack.h \
		attacker.h \
		smartattacker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

medpack.o: medpack.cpp medpack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o medpack.o medpack.cpp

player.o: player.cpp player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

zombie.o: zombie.cpp zombie.h \
		enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zombie.o zombie.cpp

zombie_invasion.o: zombie_invasion.cpp zombie_invasion.h \
		enemy.h \
		player.h \
		zombie.h \
		blocker.h \
		medpack.h \
		attacker.h \
		smartattacker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zombie_invasion.o zombie_invasion.cpp

smartattacker.o: smartattacker.cpp smartattacker.h \
		enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smartattacker.o smartattacker.cpp

moc_zombie_invasion.o: moc_zombie_invasion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_zombie_invasion.o moc_zombie_invasion.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

